import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Customisator Image",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="h-full">
      <body
        suppressHydrationWarning={true}
        className={clsx(inter.className, "h-full")}
      >
        {children}
      </body>
    </html>
  );
}
